export CMAKE_PREFIX_PATH=$MY_LIBRARY_PATH:/home/wing/intel/mkl:$CMAKE_PREFIX_PATH
export CMAKE_EXE=/home/wing/exe/bin/cmake
$CMAKE_EXE -DBUILD_SHARED_LIBS=ON -DUSE_LMDB=ON -DBLAS=MKL -DUSE_LEVELDB=OFF -DUSE_NCCL=ON -DALLOW_LMDB_NOLOCK=ON ..
